export { AboutScreen } from './AboutScreen/AboutScreen';
export { CalculationScreen } from './CalculationScreen/CalculationScreen';
export { ContactScreen } from './ContactScreen/ContactScreen';
export { DetailScreen } from './DetailScreen/DetailScreen';
export { HomeScreen } from './HomeScreen/HomeScreen';
export { PariteScreen } from './PariteScreen/PariteScreen';
export { SettingsScreen } from './SettingsScreen/SettingsScreen';
export { LoginScreen } from './LoginScreen/LoginScreen';
export { RegisterScreen } from './RegisterScreen/RegisterScreen';
