import { StyleSheet, Dimensions } from 'react-native';
import { colors } from '../../global/constants/variables/colors';

const { width, height } = Dimensions.get('screen');

export default StyleSheet.create({
  container: {
    position: 'absolute',
    width,
    height,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.black_95,
  },
  hiddenClose: {
    position: 'absolute',
    flex: 1,
    width,
    height: height,
    zIndex: 998,
    backgroundColor: 'transparent',
  },
  containerContent: {
    backgroundColor: '#eeeeee',
    borderWidth: 1,
    borderColor: colors.black,
    minWidth: (width * 2) / 3,
    maxWidth: width - 32,
    minHeight: 100,
    justifyContent: 'center',
    borderRadius: 8,
    padding: 16,
    zIndex: 999,
    shadowColor: colors.black,
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 0.75,
    shadowRadius: 8,
    elevation: 5,
  },
  title: {
    fontSize: 20,
    fontStyle: 'normal',
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 16,
  },
  subtitle: {
    fontSize: 14,
    fontStyle: 'normal',
    fontWeight: 'normal',
    textAlign: 'center',
    marginBottom: 16,
  },
  buttons: {
    flexDirection: 'row',
    height: 40,
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 16,
  },
  cancel: {
    flex: 1,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#eeeeee',
    borderWidth: 1,
    borderColor: colors.black,
    borderRadius: 8,
  },
  cancelTxt: {
    fontSize: 14,
    fontStyle: 'normal',
    fontWeight: 'normal',
    textAlign: 'center',
    color: colors.black,
  },
  confirm: {
    flex: 2,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.black,
    borderWidth: 1,
    borderColor: colors.black,
    borderRadius: 8,
  },
  confirmTxt: {
    fontSize: 14,
    fontStyle: 'normal',
    fontWeight: 'normal',
    textAlign: 'center',
    color: '#eeeeee',
  },
});
